// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xfbdzfpsgclqgilzioqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhmYmR6ZnBzZ2NscWdpbHppb3F5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODgxMTg3MjAsImV4cCI6MjEwMzY5NDcyMH0.pspUXtYHpZ3m38YOIjLPCPN23bF_fEmCPXSZ5w3CWSQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});